// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MrTS_EventNames","status":true,"description":"Allows events to show their names above them.","parameters":{"Default Range":"5","Font Size":"24","Font Name":"GameFont","Fade":"True","Fade Timer":"30"}}
];
